export const NFT_CONTRACT_ADDRESS =
  process.env.NEXT_PUBLIC_NFT_CONTRACT_ADDRESS;
export const TOKEN_ADDRESS = process.env.NEXT_PUBLIC_TOKEN_ADDRESS;
export const PAY_PROCESSOR_ADDRESS =
  process.env.NEXT_PUBLIC_PAY_PROCESSOR_ADDRESS;
export const NETWORK_DOMAIN = process.env.NEXT_PUBLIC_NETWORK_DOMAIN;
